### ISSUE TITLE
Q: Comparison with LiteServ?

### ISSUE THREAD

**Issue by snej** [couchbaselabs/couchbase-lite-local#4]
How does this compare to the LiteServ app that comes with Couchbase Lite? It's Mac-only, of course, but it's a lot lighter weight because it doesn't drag in the JVM. (Not to mention that Macs don't come with a JVM anymore.)

**Comment by sideshowcoder** [comment]
Actually I created it as an experiment to run on my Pi as well as on my mac and to explore what the bare bones features are. So haven't really looked into the LiteServ app.

**Comment by snej** [comment]
Cool. Sounds like a good non-Mac equivalent of LiteServ, which is definitely useful. How does it perform on the Pi?

**Comment by sideshowcoder** [comment]
Works well, it takes a long time to startup but when the JVM has warmed up it works great.

**Comment by stepnoy** [comment]
There is my two cents I want to make some dedicated "db server" based on PI. Therefore what I missed from this solution is an ability to fixate credentials from start to start. Also I have some issues with db creation. It is described is neighbor issue.

**Comment by sideshowcoder** [comment]
@stepnoy  As this is implemented on master now I will close this also thanks to @snej for pointing out LiteServ as the way to go on Mac :+1:
