### ISSUE TITLE
couchbase-lite-java-core update to 1.0.3

### ISSUE THREAD

**Issue by aminjam** [couchbaselabs/couchbase-lite-local#7]
Is there any way you could possibly upgrade [couchbase-lite-java-core](https://github.com/couchbase/couchbase-lite-java-core/releases) to the latest version? I am getting a similar error to https://github.com/couchbase/couchbase-lite-java-core/issues/252 that I think it's resolved in the later versions.

**Comment by sideshowcoder** [comment]
Yeah sure, will do when I'm at a computer again, or you could take a stab at it in the meantime. All needed is swapping out the jars in the vendor folder and running `rake jar` as seen in the Readme. As they are non native jars that needs no compiler chain or anything so should be easy enough I guess. `rake test` should tell you if it was successful ;)

**Comment by aminjam** [comment]
yeah, I even forked the repo, but `bundle install` was giving me an error, and I don't know much about ruby, so my googling didn't take me far. 

```
Fetching gem metadata from https://rubygems.org/...
Resolving dependencies...
Could not find gem 'couchbase_lite_local (>= 0) java' in source at ..
Source contains 'couchbase_lite_local' at: 0.0.3
```

Then I figured I should install `couchbase_lite_local` gem, so I ran `gem install couchbase_lite_local`

```
ERROR:  Could not find a valid gem 'couchbase_lite_local' (>= 0) in any repository
```

At this point I gave up my dreams of becoming rubyist, and I figured I should ask here from the experts.

**Comment by sideshowcoder** [comment]
Actually the only Problem you have there is running it with ruby not jruby which is build on Java http://jruby.org/download sorry about the confusion there :(. No worries if you don't get it to work I'll fix asap

**Comment by aminjam** [comment]
Thanks, I was able to fork and update the `.jar` files, but it seems like the new version breaks the `_replicate` endpoint, so I wouldn't want to send a pull request and break your build.

**Comment by sideshowcoder** [comment]
There were some jars missing in my update first but I think I found everything, do you mind trying the jar I created? https://s3.amazonaws.com/sideshowcoder/couchbase-lite-local.jar I played around with it a little and it seems to work. The updates are in the `updating-jars-to-1.0.3` branch.

**Comment by aminjam** [comment]
Thank you. Everything is loading up perfect for me without any error. I really wanted to get the cb_lite working for [the demo here](https://github.com/aminjam/hipops/tree/master/devops/scenarios/hipops-CBServerSyncGateway-dev). I ended up just using Todo-Lite-PhoneGap instead. I wish there was more documentation around how to call the specific `_replicate` endpoint for cb_lite from REST endpoint.
